title: Les Tontons Codeurs
brand: les tontons cod[3]urs
subject: Expérimentations ludiques sur microcontrôleurs
copyright: 2018

collections:
  guides:
    output: true
    permalink: /guides/:path/

defaults:
  - scope:
      type: "posts"
    values:
      layout: article
  - scope:
      type: "guides"
    values:
      layout: article

permalink: pretty

# excerpt_separator: "<!--more-->"

highlighter: rouge

sass:
  style: compressed