# baseurl: /tontons
baseurl: ''
title: Les Tontons Codeurs
brand: les tontons cod[3]urs
copyright:
    start: 2018
    name: Les Tontons Codeurs

collections:
    tutoriels:
        output: true
        permalink: /tutos/:path/

defaults:
    - scope:
        type: "tutoriels"
      values:
        layout: article

sass:
    style: compressed