# baseurl: '/tontons'
title: Les Tontons Codeurs
brand: les tontons cod[3]urs
copyright: 2018

collections:
  tutos:
    output: true
    permalink: /tutos/:path/

defaults:
  - scope:
      type: "posts"
    values:
      layout: article
  - scope:
      type: "tutos"
    values:
      layout: article

permalink: pretty

sass:
  style: compressed